### ISSUE TITLE
Is the bare repo technique easier to deal with?

### ISSUE THREAD

**Issue by alxn** [prashantv/dotfiles#1]
https://news.ycombinator.com/item?id=11071754

**Comment by prashantv** [comment]
Looks like a blog post was written about this too (based on that comment), https://www.atlassian.com/git/tutorials/dotfiles

I checked it out, it's an interesting approach, but I don't like some aspects,
 * The use of a custom alias (since the `.git` is in a separate folder) means muscle memory for git will be thrown off a little, the clone is non-trivial too
 * The installation script does more than symlink, it actually clones/pulls git repos too, which would need a script anyway
 * I don't want everything in the repo to be at the root of my home dir (e.g., the install script)

**Comment by alxn** [comment]
Yeah the custom alias (which that breaks shell completion) is a bit of a non-starter.
